# -*- coding: utf-8 -*-
"""first-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1qnKYB7PEVnprBRXo88tFf80h5LT5Ew

# **First ML project**

# **Load data**
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/dataprofessor/data/master/delaney_solubility_with_descriptors.csv')
df

"""# **Data preparation**

## Data separation as X and Y
"""

y = df['logS']
y

X = df.drop('logS', axis=1)
X

"""## Data splitting"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=100)

X_train

X_test

"""# **Model Building**

## **Linear Regression**

**Training the model**
"""

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

"""**Applying the model to make a prediction**"""

y_lr_train_pred = lr.predict(X_train)
y_lr_test_pred = lr.predict(X_test)

y_lr_train_pred

y_lr_test_pred

"""**Evaluate model performance**"""

from sklearn.metrics import mean_squared_error, r2_score

lr_train_mse = mean_squared_error(y_train, y_lr_train_pred)
lr_train_r2 = r2_score(y_train, y_lr_train_pred)

lr_test_mse = mean_squared_error(y_test, y_lr_test_pred)
lr_test_r2 = r2_score(y_test, y_lr_test_pred)

print('LR MSE (Train): ', lr_train_mse)
print('LR R2 (Train): ', lr_train_r2)
print('LR MSE (Test): ', lr_test_mse)
print('LR R2 (Test): ', lr_test_r2)

